### ISSUE TITLE
🐛 GraphLogger NPE when checking status of runs (possible race condition)

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/workflow-graph-node#61]
Only occurred once, but its possible that it is a race condition when polling the rdpc gateway before the workflow shows up. 

Stacktrace:
```
Caused by: java.lang.NullPointerException
	at org.icgc_argo.workflowgraphnode.logging.GraphLogger.graphLog(GraphLogger.java:139) ~[classes!/:?]
	at org.icgc_argo.workflowgraphnode.logging.GraphLogger.info(GraphLogger.java:24) ~[classes!/:?]
	at org.icgc_argo.workflowgraphnode.rabbitmq.NodeConfiguration.lambda$runningToComplete$0(NodeConfiguration.java:101) ~[classes!/:?]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:189) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.tryOnNext(FluxHandleFuseable.java:119) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallyFuseableConditionalSubscriber.tryOnNext(FluxDoFinally.java:248) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.tryOnNext(FluxPeekFuseable.java:522) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.tryOnNext(FluxPeekFuseable.java:522) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallyFuseableConditionalSubscriber.tryOnNext(FluxDoFinally.java:248) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.tryOnNext(FluxPeekFuseable.java:522) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblyConditionalSubscriber.tryOnNext(FluxOnAssembly.java:529) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:866) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:939) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:79) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.trySchedule(FluxPublishOn.java:759) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.onNext(FluxPublishOn.java:704) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.rabbitmq.Sender$PublishConfirmSubscriber$1.handleAckNack(Sender.java:953) [reactor-rabbitmq-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at reactor.rabbitmq.Sender$PublishConfirmSubscriber$1.handleAck(Sender.java:928) [reactor-rabbitmq-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at com.rabbitmq.client.impl.ChannelN.callConfirmListeners(ChannelN.java:498) [amqp-client-5.7.3.jar!/:5.7.3]
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:369) [amqp-client-5.7.3.jar!/:5.7.3]
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182) [amqp-client-5.7.3.jar!/:5.7.3]
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114) [amqp-client-5.7.3.jar!/:5.7.3]
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:672) [amqp-client-5.7.3.jar!/:5.7.3]
	at com.rabbitmq.client.impl.AMQConnection.handleReadFrame(AMQConnection.java:621) [amqp-client-5.7.3.jar!/:5.7.3]
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:160) [amqp-client-5.7.3.jar!/:5.7.3]
```

**Comment by lepsalex** [comment]
The null pointer issue has been resolved however I would still like to understand why `.doOnNext(tx -> GraphLogger.info(tx, "Completed: %s", tx.get()))` is being called after the transactions are being committed. I have some ideas on why this might be happening but I want to spend a little more time nailing this down.
